### ISSUE TITLE
Back button not working when in portrait orientation.

### ISSUE THREAD

**Issue by spadez00** [pokedens/pokedens.github.io#1]
On my Galaxy S10+ the back button doesn't actually do anything for some reason. The only way I can actually see the map is to use landscape but then everything is all squished. It's just a minor inconvenience, but thought you should know regardless. Thank you for the awesome app!

**Comment by Treeston** [comment]
Ah, Samsung has their own browser. Managed to reproduce, will investigate.

**Comment by spadez00** [comment]
Guessing it was an easy fix lol? Working perfectly now, thanks! (I was using Chrome not Samsung's browser, but eh.) ¯\_(ツ)_/¯

**Comment by Treeston** [comment]
Yeah, Samsung browser is also based off Chromium. No idea why Desktop Chrome wouldn't exhibit the issue for me when I tried.
